jeu: main.o music.o store.o conditions.o enigmestat.o initialiser.o  affichage.o  animations.o  collisionTrigo.o  score_et_vies.o collision_pp.o  collision_bb.o  deplacer_hero_souris.o  free.o enig_file.o new.o
	gcc main.o music.o store.o conditions.o enigmestat.o initialiser.o  affichage.o  animations.o  collisionTrigo.o  collision_bb.o  score_et_vies.o collision_pp.o  deplacer_hero_souris.o  free.o enig_file.o new.o -o jeu -g -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -lm
main.o: main.c
	gcc -c main.c -g
music.o: music.c
	gcc -c music.c -g
store.o: store.c
	gcc -c store.c -g
conditions.o: conditions.c
	gcc -c conditions.c -g
enigmestat.o: enigmestat.c
	gcc -c enigmestat.c -g
initialiser.o: initialiser.c
	gcc -c initialiser.c -g
affichage.o: affichage.c
	gcc -c affichage.c -g 
animations.o: animations.c
	gcc -c animations.c -g
collisionTrigo.o: collisionTrigo.c
	gcc -c collisionTrigo.c -g
collision_pp.o: collision_pp.c
	gcc -c collision_pp.c -g
collision_bb.o: collision_bb.c
	gcc -c collision_bb.c -g
score_et_vies.o: score_et_vies.c
	gcc -c score_et_vies.c -g
deplacer_hero_souris.o: deplacer_hero_souris.c
	gcc -c deplacer_hero_souris.c -g
free.o: free.c
	gcc -c free.c -g
enig_file.o: enig_file.c
	gcc -c enig_file.c -g
new.o: new.c
	gcc -c new.c -g
